package core

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
)

var validKeyRegex = regexp.MustCompile(`^[a-zA-Z_][a-zA-Z0-9_]*$`)

// IsValidKey checks if the given string is a valid POSIX environment variable identifier.
// Valid keys must start with an ASCII letter or underscore, followed by letters, digits, or underscores.
func IsValidKey(key string) bool {
	return validKeyRegex.MatchString(key)
}

// ParseEnvFile reads a file at the given path and parses it as a KEY=VALUE format.
// It returns a map of environment variables or an error.
func ParseEnvFile(filePath string) (map[string]string, error) {
	file, err := os.Open(filePath)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	envVars := make(map[string]string)
	scanner := bufio.NewScanner(file)

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Ignore empty lines and comments
		if len(line) == 0 || strings.HasPrefix(line, "#") {
			continue
		}

		// Support "export KEY=VALUE" prefix if present
		if strings.HasPrefix(line, "export ") {
			line = strings.TrimSpace(strings.TrimPrefix(line, "export "))
		}

		// Split line into key and value
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue // Ignore malformed lines
		}

		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])

		// Handle quoted values: "value" or 'value'
		if (strings.HasPrefix(value, "\"") && strings.HasSuffix(value, "\"")) ||
			(strings.HasPrefix(value, "'") && strings.HasSuffix(value, "'")) {
			if len(value) >= 2 {
				value = value[1 : len(value)-1]
			}
		}

		if key != "" && IsValidKey(key) {
			envVars[key] = value
		}
	}

	if err := scanner.Err(); err != nil {
		return nil, err
	}

	return envVars, nil
}

// WriteEnvFile saves a map of environment variables to the specified file path,
// formatted neatly as KEY="VALUE" with keys in sorted order.
func WriteEnvFile(filePath string, envVars map[string]string) error {
	keys := make([]string, 0, len(envVars))
	for k := range envVars {
		if IsValidKey(k) {
			keys = append(keys, k)
		}
	}
	sort.Strings(keys)

	var builder strings.Builder
	builder.WriteString("# Generated by simplyenv\n")
	for _, k := range keys {
		// Escape backslashes and double quotes in value
		val := envVars[k]
		val = strings.ReplaceAll(val, "\\", "\\\\")
		val = strings.ReplaceAll(val, "\"", "\\\"")
		builder.WriteString(fmt.Sprintf("%s=\"%s\"\n", k, val))
	}

	return os.WriteFile(filePath, []byte(builder.String()), 0644)
}

// SetEnvVar adds or updates an environment variable in the target file.
func SetEnvVar(filePath, key, value string) error {
	if !IsValidKey(key) {
		return fmt.Errorf("invalid environment variable key: %q (must match ^[a-zA-Z_][a-zA-Z0-9_]*$)", key)
	}
	vars, err := ParseEnvFile(filePath)
	if err != nil {
		if os.IsNotExist(err) {
			vars = make(map[string]string)
		} else {
			return err
		}
	}
	vars[key] = value
	return WriteEnvFile(filePath, vars)
}

// DeleteEnvVar removes an environment variable from the target file.
func DeleteEnvVar(filePath, key string) error {
	if !IsValidKey(key) {
		return fmt.Errorf("invalid environment variable key: %q", key)
	}
	vars, err := ParseEnvFile(filePath)
	if err != nil {
		return err
	}
	delete(vars, key)
	return WriteEnvFile(filePath, vars)
}
